[general]
log4rs_config = "stegos-log4rs.toml"

[keychain]
private_key = "testing/node02/stegos.skey"
public_key = "testing/node02/stegos.pkey"

[network]
node_id = "node02"
bind_ip = "127.0.0.1"
bind_port = 10056
advertise_local_ips = false

seed_nodes = [
    "/ip4/127.0.0.1/tcp/10055",
    "/ip4/127.0.0.1/tcp/10057",
]

advertised_addresses = [
    "/ip4/127.0.0.1/tcp/10056",
]
